name: Deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Build and Make image, Push image and Pull image and run in instance 
      uses: appleboy/ssh-action@master
      with:
        host: applytics.in
        username: git_bot
        key: ${{ secrets.SERVER_PRIVATE_KEY }}
        script: ls
